version: "3.7"
services:
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.6.2
    ports:
      - 5601:5601
    volumes:
      - ./kibana/config.yml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      - elasticsearch
    networks:
      - elk

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.0
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
      discovery.type: "single-node"
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    volumes:
      - ./elasticsearch/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - elk

# volumes:
#   esdata:

networks:
  elk:
    driver: bridge


# https://www.edc4it.com/blog/docker-kibana-elasticsearch-beats-tutorial
# https://faun.pub/nginx-logs-monitoring-using-elk-stack-docker-4b64f46e989
